name: cmip6-analysis
channels:
  - conda-forge
dependencies:
  - python =3.11
  - numpy =1.26.*
  - pandas =2.2.*
  - xarray =2024.5.*
  - netCDF4 =1.6.*
  - matplotlib =3.9.*
  - cartopy =0.23.*
  - jupyterlab =4.*
  - nbval =0.11.*
  - pytest =8.*
  - papermill =2.*
  - black =24.*
  - ruff =0.4.*
  - pydocstyle =6.*
